backend:
  name: github
  repo: udithv/super-simple-gatsby-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/articles/
    create: true
    fields: 
      - { name: date, label: Date, widget: date } 
      - { name: title, label: Title }
      - { name: mediumurl, label: "Medium URL", widget: string, required: false}
      - { name: githubrepourl, label: "Github Repo URL", widget: string, required: false}
      - { name: body, label: Body, widget: markdown } 
      - { name: tags, label: Tags, widget: list }